### ISSUE TITLE
Little typo in 1st time tutorial

### ISSUE THREAD

**Issue by anmonteiro** [auditorium/auditorium#152]
So I have just registered for auditorium and spotted a little typo in the first tutorial, which i found [here](https://github.com/auditorium/auditorium/blob/f65dbb7985e7dba8937268e8139670f563695b3a/src/config/locales/en.yml#L903)

easy fix, just change 'wrtie' to 'write', I can send a pull request if necessary, just didn't think it would be of importance.

**Comment by PhilippMatthes** [comment]
RIP
